# Generated automatically from Makefile.in by configure.
#
# Copyright 2002,2004 The Apache Software Foundation.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
#
# $Log: Makefile.in,v $
# Revision 1.3  2004/09/08 13:56:43  peiyongz
# Apache License Version 2.0
#
# Revision 1.2  2004/07/09 16:27:25  peiyongz
# Build on HP-Itanium, aCC A.05.52
#
# Revision 1.1  2002/08/19 18:35:56  tng
# [Bug 6467] Installing Xerces C++ on cygwin environment.
#
#

PLATFORM = LINUX
CC  = gcc
CXX = c++
CXXVER = 
GCC = yes
GXX = yes
CXXFLAGS = -g -O2
CFLAGS = -g -O2
PREFIX = /usr/local
PREFIX_INCLUDE = ${PREFIX}/include/xercesc
LDFLAGS = 
LIBS = 
OSVER = 
USELIBWWW = 
MESSAGELOADER = 
TRANSCODER = 
THREADS = 

MODULE = util
SUBMODULE = Transcoders/Cygwin

include ../../../Makefile.incl

CPP_PUBHEADERS = CygwinTransService.hpp

CPP_OBJECTS = CygwinTransService.$(TO)

include ../../Makefile.util.submodule
